{
    "cloud":"AzurePublicCloud",
    "tenantId": "{{.Values.azAccount.tenantId}}",
    "subscriptionId": "{{.Values.azAccount.id}}",
    "aadClientId": "{{.Values.aks.spn.appId}}",
    "aadClientSecret": "{{.Values.aks.spn.pwd}}",
    "resourceGroup": "{{.Values.aks.nodeResourceGroup}}",
    "location": "{{.Values.aks.location}}",
    "vmType": "standard",
    "subnetName": "aks-subnet",
    "securityGroupName": "{{.Values.aks.networkSecurityGroup}}",
    "vnetName": "{{.Values.aks.virtualNetwork}}",
    "vnetResourceGroup": "{{.Values.aks.resourceGroup}}",
    "routeTableName": "{{.Values.aks.routeTable}}",
    "primaryAvailabilitySetName": "{{.Values.aks.availabilitySet}}",
    "primaryScaleSetName": "",
    "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
    "cloudProviderBackoffExponent": 1.5,
    "cloudProviderBackoffDuration": 5,
    "cloudProviderBackoffJitter": 1,
    "cloudProviderRatelimit": true,
    "cloudProviderRateLimitQPS": 3,
    "cloudProviderRateLimitBucket": 10,
    "useManagedIdentityExtension": false,
    "userAssignedIdentityID": "",
    "useInstanceMetadata": true,
    "loadBalancerSku": "Basic",
    "excludeMasterFromStandardLB": false,
    "providerVaultName": "",
    "maximumLoadBalancerRuleCount": 250,
    "providerKeyName": "k8s",
    "providerKeyVersion": "{{.Values.aks.version}}"
}